# Generated by Django 4.2.7 on 2024-10-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio_unitario',
        ),
    ]
