# Generated by Django 4.2.7 on 2024-10-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_detalleventa_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
